CREATE TABLE tb_order (id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY, totalamount DECIMAL(10, 2) NOT NULL);
CREATE TABLE tb_product (id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,name VARCHAR(255) NOT NULL,description TEXT, price DECIMAL(10, 2)  NULL,stock INTEGER  NULL);
CREATE TABLE order_items (id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,orderId BIGINT NOT NULL, productId BIGINT NOT NULL,quantity INTEGER NOT NULL, unitPrice DECIMAL(10, 2) NOT NULL);






